### ISSUE TITLE
加强一波英雄 DDL 9.24

### ISSUE THREAD

**Issue by puck1609** [windybirth/windy10v10ai#406]
- [x] 1. ug 移除大招并更换新大招
- [x] 2. lina 增强叠炽魂的玩法，增强A杖大视觉效果
- [x] 3. 小鱼
- [x] 4. 电棍
- [x] 5. 剧毒
- [x] 6. 军团

**Comment by windybirth** [comment]
UG折射已经很强了，移除大招可能会跟A杖技能冲突，要注意。
lina天赋想要更换成什么样的？
其他OK

**Comment by puck1609** [comment]
小鱼 电棍 纯弟弟加强 之前没法玩
剧毒 电棍 更新后增强推进能力，目前版本很容易变成能不能推塔全看物理大哥心情的局面

**Comment by puck1609** [comment]
剩下ug没做

**Comment by puck1609** [comment]
lina 新加的文本有一点瑕疵，但是不影响实际效果。文本瑕疵和底层逻辑有关系，感觉不好改

**Comment by puck1609** [comment]
幽鬼上线之后100%会受热议

**Comment by puck1609** [comment]
加一个小改动：
萨尔 E框延迟时间减少
