### ISSUE TITLE
强袭祭品不减对方建筑盔甲？

### ISSUE THREAD

**Issue by dan0dbfe** [windybirth/windy10v10ai#570]
普通AC减对方建筑盔甲
升级成 `item_vladmir_2` 过后对方建筑没减盔甲的 debuff

有可能是因为 `modifier_item_vladmir_2_enemy_aura_emitter` 的 `Aura_Types` 缺了 `DOTA_UNIT_TARGET_BUILDING`

**Comment by windybirth** [comment]
@dan0dbfe 
感谢您提出的问题。
为了限制带线偷塔，强袭祭品有意设计成不减对方建筑护甲。
物品描述里也添加不减建筑护甲的说明，并不是BUG。
