### ISSUE TITLE
做个可以选技能英雄

### ISSUE THREAD

**Issue by mimihua** [windybirth/Windy10v10AI#7]
就像OMG那样可以选择技能
或者可以摇色子，抽卡的那种感觉的 选技能升级技能
比如击杀敌人随机掉落装备 ，升级图鉴
再结合一下大富翁摇色子，加攻击 减攻击的那种。
一夜破产 怎么样？？？？

**Comment by mimihua** [comment]
就算大家都有钱出装备 踏🐎的也要把装备的属性 搞成个随机值
这样就刷的快，说不定抽出个白卡 也要从头刷！

**Comment by windybirth** [comment]
需求不明 复杂度过高，有待商榷。
提高随机性挺好的，需要具体方案

**Comment by windybirth** [comment]
目前能想到的是 高等级装备死亡概率性随机掉落。
现在EX咖喱棒是50%概率掉落，可以加入大核荣耀等道具，死亡时候20%？概率掉落，一夜回到解放前

**Comment by windybirth** [comment]
并且刃甲的存在可以确保装备碾压也是有可能暴毙的

**Comment by mimihua** [comment]
首先说说 你能改动的范围
玩家向：
1.加入一个新装备
2.修改旧装备
3.加入一个新英雄
4.改旧英雄的技能
4-1.旧英雄的技能值随便改 包括减技能 加技能 ，让玩家自选技能
AI向：
1.加入新的高级AI？
2.待定

**Comment by windybirth** [comment]
玩家向：
1.加入一个新装备
2.修改旧装备
4.改旧英雄的技能
----------------只能改这些-------------
玩家自选技能极其复杂！！！从选技能UI到技能生效都需要从0写代码，除非有个团队，不然不用考虑。

**Comment by mimihua** [comment]
团队的话可以邀请@nj005py 加入
装备的数值能再购买后随机嘛？
可以在商店里面加入抽卡池嘛？

**Comment by windybirth** [comment]
目前的改动都是以既存功能为基础进行的调整，大幅度改动能做什么可以参考下面这个网站，里面有一些例子可以借鉴，编程难度（主要是不熟悉V社的API）会小很多。
https://moddota.com/
V社API文档
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/Getting_Started

**Comment by windybirth** [comment]
能不能我也不知道，请自行参阅上面2个文档。

**Comment by windybirth** [comment]
或者参考别人做好的图 也是个不错的选择
