### ISSUE TITLE
[BUG]神器天地同寿护甲错误计算

### ISSUE THREAD

**Issue by Bowen-Zhai** [windybirth/windy10v10ai#769]
**BUG 类型**

- [ ] 技能
- [ √] 物品
- [ ] 英雄
- [ ] AI
- [ ] 用户界面
- [x] 其他
![Uploading Screenshot 2024-01-06 094202.png…]()
![Uploading Screenshot 2024-01-06 094202.png…]()

**描述这个 BUG**
天地同寿（大反甲）护甲加法计算变成了减法计算。

**复现步骤**
两个反甲2 都+20 护甲，合成天地同寿后-40 护甲。

**期望的行为**
请修正计算。

**截图**

**Comment by windybirth** [comment]
@Bowen-Zhai 
感谢您的反馈，这是故意设计成这样的，取同归于尽的意思，所以叫天体同寿自爆卡车
