### ISSUE TITLE
[BUG] Game crashes on player consuming Wings of haste

### ISSUE THREAD

**Issue by DocterZed** [windybirth/windy10v10ai#839]
**Bug type**

- [ ] Ability
- [x] Item
- [ ] Hero
- [ ] Bot
- [ ] UI
- [ ] Other

**Describe the bug**

The game crashes as soon as a player attempts to consume the Wings of haste boots item.

**To Reproduce**

1. Start a game
2. Buy the "Wings of haste" item
3. Game immediately crashes

**Expected behavior**
Should be able to consume custom items

**Comment by windybirth** [comment]
Thank you for reporting, bug is fixed.
