### ISSUE TITLE
Silencer - Glaives of wisdom doesn't steal intelligence from enemy heroes on attack

### ISSUE THREAD

**Issue by barik-koshmarik** [windybirth/windy10v10ai#870]
**Bug type**

- [x] Ability
- [ ] Item
- [ ] Hero
- [ ] Bot
- [ ] UI
- [ ] Other

**Describe the bug**
Silencer - Glaives of wisdom doesn't steal intelligence from enemy heroes on attack
*To Reproduce**

1. Pick Silencer
2. add 1 skillpoint to Glaives of wisdom
3. Switch on autocast of glaives of wisdom
4. Attack enemy hero

**Expected behavior**
Glaives of wisdom steal intellect from enemy hero on every attack

**Screenshots**

**Comment by windybirth** [comment]
It seems to have been fixed in a past update
