### ISSUE TITLE
[FEATURE] Rework Member Experience

### ISSUE THREAD

**Issue by dfyzb0** [windybirth/windy10v10ai#989]
**Feature Request**

- [ ] Ability
- [ ] Item
- [ ] Hero
- [ ] Bot
- [ ] UI
- [ X ] Other

**Describe the bug**
Leveling for members is still very slow. Having the experience earned for each game also apply to the member level would help make the leveling system more reasonable while still encouraging people to purchase the member pass.

**Expected behavior**
With the current leveling system it will take years of daily play to reach final level. 

**To Reproduce**
N/A
**Screenshots**
N/A

**Comment by windybirth** [comment]
Final level is not designed to be reachable.
Battle point is a system independent of members.

**Comment by dfyzb0** [comment]
@windybirth This is a suggestion to encourage more people to pay you for membership. Here's the breakdowns for your current leveling system:
To get to level 61 (1/3 of your leveling system) a member must play 3.12 games, every single day, for 1 year. A non member must play 7.97 games a day, for 1 year. 

To get to level 92 (halfway through your leveling system) a member must play 10.18 games, every single day, for 1 year. A non-member must play 18 games a day, for 1 year.  

The game loses a lot of its motivation to continue playing when leveling starts to occur monthly, and only from playing the game every single day.
