### ISSUE TITLE
[BUG] Centaur Warrunner's Horsepower facet movement speed irregularities

### ISSUE THREAD

**Issue by dfyzb0** [windybirth/windy10v10ai#990]
**Bug type**

- [ ] Ability
- [ ] Item
- [ X ] Hero
- [ ] Bot
- [ ] UI
- [ ] Other

**Describe the bug**
Centaur Warrunner's Horsepower Facet does not stack with points based movement speed increases (boots, battle level bonuses). The interaction is finicky.

**Expected behavior**
Centaur Warrunner should receive 30% of his strength as bonus movement speed 

**To Reproduce**
Use Horsepower facet, purchase Wings of haste, allocate Battle pass points in to movement speed. Level up and/or increase Centaur's strength and observe his movement speed as you do.

**Screenshots**
Screenshot 1: +275 movement speed (should be +323)
161 Strength * .3 = 48.3 + 100 (boots) + 175 (battle points) = 323 bonus movement speed

![image](https://github.com/user-attachments/assets/174ac014-6bea-4477-9355-551fa3d3bfd1)

Screenshot 2: +275 movement speed (should be +295)
66 Strength * .3 = 19.8 + 100 (boots) + 175 (battle points) = 295 bonus movement speed

![image](https://github.com/user-attachments/assets/a98692c5-2bc1-4218-8007-29f272312fd6)

Screenshot 3: +275 movement speed (should be +348)
244 Strength * .3 = 73.2 + 100 (boots) + 175 (battle points) = 348 bonus movement speed

![image](https://github.com/user-attachments/assets/013c322c-3b79-46f7-95d2-87b4f2127b98)

Screenshot showing +175 MS from battle pass
![image](https://github.com/user-attachments/assets/b232b711-578a-4d34-ba65-723c83790b9b)

**Comment by windybirth** [comment]
https://www.dota2.com/hero/centaurwarrunner

It is same as Dota2 described
![image](https://github.com/user-attachments/assets/05d76333-4d5b-4520-980a-3815b700f807)

**Comment by dfyzb0** [comment]
@windybirth What about the +175 movement speed bonus from the battle points?
